# Generated by Django 3.0.2 on 2020-05-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('cont_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('contact_num', models.IntegerField(verbose_name='Contact Number')),
                ('company_type', models.CharField(max_length=50, verbose_name='Company Type')),
                ('address', models.CharField(max_length=90, verbose_name='Address Line 1')),
                ('address_2', models.CharField(max_length=90, verbose_name='Address Line 2')),
                ('landmark', models.CharField(max_length=50, verbose_name='Landmark')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pincode', models.IntegerField(verbose_name='Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_type', models.CharField(max_length=50)),
                ('Invoice_num', models.CharField(max_length=10)),
                ('Date', models.DateField(blank=True)),
                ('Dispatch_through', models.CharField(max_length=50)),
                ('Due_date', models.DateField(blank=True)),
                ('Bank', models.CharField(max_length=20)),
                ('Payment_type', models.CharField(max_length=20)),
                ('Payment_note', models.TextField(max_length=50)),
                ('T_c', models.TextField(max_length=100)),
                ('Document_note', models.TextField(max_length=100)),
                ('Cust_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.CustomerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=10)),
                ('gstin_number', models.CharField(max_length=15)),
                ('address_1', models.CharField(max_length=90)),
                ('address_2', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.CharField(max_length=40)),
                ('password_1', models.CharField(max_length=40)),
                ('password_2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Hsn_code', models.CharField(max_length=20)),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Cgst', models.IntegerField()),
                ('Sgst', models.IntegerField()),
                ('Igst', models.IntegerField()),
                ('Cess', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Invoice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.Invoice_Details')),
                ('companyName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.OrganisationDetails')),
            ],
        ),
        migrations.AddField(
            model_name='invoice_details',
            name='companyName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.OrganisationDetails'),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='companyName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.OrganisationDetails'),
        ),
    ]
