# Generated by Django 3.0.2 on 2020-06-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_invoice_details_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='qrcode',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
