# Generated by Django 3.0.2 on 2020-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200619_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='qrcode',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
