# Generated by Django 3.0.2 on 2020-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20200619_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Total',
            field=models.FloatField(),
        ),
    ]
