# Generated by Django 4.1.2 on 2023-04-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20200624_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('companyName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails')),
            ],
        ),
    ]
