# Generated by Django 4.1.2 on 2023-04-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_addproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='Price',
        ),
    ]
